### ISSUE TITLE
Action is not available in the Marketplace

### ISSUE THREAD

**Issue by mikaeldui** [46elks/gh-actions-sms#1]
I'm not able to find the action in the [GitHub Actions Marketplace](https://github.com/marketplace?type=actions), can it be added there?

**Comment by reinefjord** [comment]
Hi, sorry about the lack of response. There was an issue on GitHub's end that made it impossible to publish this action. It has been resolved now and the action is available [on the marketplace](https://github.com/marketplace/actions/46elks-sms)!
